# Generated by Django 5.1.5 on 2025-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsFetchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="تفعيل أو إيقاف الجلب التلقائي"
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="عدد الدقائق بين كل عملية جلب تلقائي"
                    ),
                ),
                (
                    "last_fetch_time",
                    models.DateTimeField(
                        blank=True, help_text="آخر مرة تم فيها الجلب", null=True
                    ),
                ),
            ],
        ),
    ]
