# Generated by Django 5.1.5 on 2025-06-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsFetchConfig',
        ),
    ]
