# Generated by Django 5.1.5 on 2025-06-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0002_delete_newsfetchconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFetchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.IntegerField(default=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_fetch_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
