# Generated by Django 5.1.5 on 2025-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfetchconfig',
            name='interval_minutes',
            field=models.IntegerField(default=10, help_text='عدد الدقائق بين كل جلب تلقائي'),
        ),
        migrations.AlterField(
            model_name='newsfetchconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='تفعيل أو تعطيل الجلب التلقائي'),
        ),
    ]
