# Generated by Django 5.1.5 on 2025-05-23 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("interest_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                ("news_source_id", models.AutoField(primary_key=True, serialize=False)),
                ("news_source_name", models.CharField(max_length=100)),
                ("news_source_url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "news_article_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("news_article_type", models.CharField(max_length=50)),
                ("news_article_title", models.CharField(max_length=250)),
                ("news_article_content", models.TextField()),
                ("news_article_keywords", models.TextField()),
                (
                    "news_article_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TruNexApp.interest",
                    ),
                ),
                (
                    "news_article_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TruNexApp.newssource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TruNexApp.newsarticle",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "news_article")},
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TruNexApp.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "interest")},
            },
        ),
    ]
