# Generated by Django 5.1.5 on 2025-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0002_interest_newssource_newsarticle_favorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
