# Generated by Django 5.1.5 on 2025-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0003_newssource_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="news_article_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="news_article_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
