# Generated by Django 5.1.5 on 2025-05-30 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0004_newsarticle_news_article_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
