# Generated by Django 5.1.5 on 2025-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0005_newsarticle_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="news_source_method",
            field=models.CharField(
                choices=[("api", "API"), ("rss", "RSS"), ("scraper", "Scraper")],
                default="api",
                max_length=20,
            ),
        ),
    ]
