# Generated by Django 5.1.5 on 2025-06-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0006_newssource_news_source_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="news_source_language",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
