# Generated by Django 5.1.5 on 2025-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0007_newssource_news_source_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="news_article_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="news_article_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
