# Generated by Django 5.1.5 on 2025-06-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0008_newsarticle_news_article_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSourceSectionURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        help_text="نوع القسم (مثل: politics, sports, syria, world...)",
                        max_length=30,
                    ),
                ),
                ("section_url", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_urls",
                        to="TruNexApp.newssource",
                    ),
                ),
            ],
        ),
    ]
