# Generated by Django 5.1.5 on 2025-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0009_newssourcesectionurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="news_article_region",
            field=models.CharField(
                choices=[
                    ("syria", "Syria"),
                    ("arab", "Arab World"),
                    ("world", "World"),
                ],
                default="world",
                max_length=10,
            ),
        ),
    ]
