# Generated by Django 5.1.5 on 2025-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0010_newsarticle_news_article_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="news_article_region",
            field=models.CharField(
                choices=[("syria", "syria"), ("arab", "arab"), ("world", "world")],
                default="world",
                max_length=10,
            ),
        ),
    ]
