# Generated by Django 5.1.5 on 2025-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0011_alter_newsarticle_news_article_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssourcesectionurl",
            name="section_region",
            field=models.CharField(
                blank=True,
                choices=[("syria", "syria"), ("arab", "arab"), ("world", "world")],
                help_text="النطاق الجغرافي: syria أو arab أو world (يمكن تركه فارغ)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newssourcesectionurl",
            name="section_type",
            field=models.CharField(
                blank=True,
                default="general",
                help_text="نوع القسم (مثل: politics, sports، ويمكن تركه فارغ)",
                max_length=30,
                null=True,
            ),
        ),
    ]
