# Generated by Django 5.1.5 on 2025-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0012_newssourcesectionurl_section_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newssourcesectionurl",
            name="section_type",
            field=models.CharField(
                blank=True,
                help_text="نوع القسم (مثل: politics, sports، ويمكن تركه فارغ)",
                max_length=30,
                null=True,
            ),
        ),
    ]
