# Generated by Django 5.1.5 on 2025-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0013_alter_newssourcesectionurl_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="news_article_region",
            field=models.CharField(
                choices=[("syria", "syria"), ("arab", "arab"), ("world", "world")],
                default="arab",
                max_length=10,
            ),
        ),
    ]
