# Generated by Django 5.1.5 on 2025-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0014_alter_newsarticle_news_article_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="fetch_interval_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="newssource",
            name="fetch_limit",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="newssource",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
