# Generated by Django 5.1.5 on 2025-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0015_newssource_fetch_interval_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newssource",
            name="last_fetched_at",
        ),
        migrations.AlterField(
            model_name="newssource",
            name="fetch_interval_minutes",
            field=models.IntegerField(
                default=60, help_text="الفاصل الزمني بالدقائق بين كل طلب تلقائي"
            ),
        ),
        migrations.AlterField(
            model_name="newssource",
            name="fetch_limit",
            field=models.IntegerField(
                default=10, help_text="عدد المقالات المطلوبة من المصدر"
            ),
        ),
    ]
