# Generated by Django 5.1.5 on 2025-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TruNexApp", "0016_remove_newssource_last_fetched_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
