# Generated by Django 5.1.5 on 2025-06-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruNexApp', '0017_newssource_last_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_article_is_fake',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
