# Generated by Django 5.1.5 on 2025-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruNexApp', '0018_newsarticle_news_article_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_article_fake_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
